services:
  load-balancer:
    image: traefik:v3
    restart: unless-stopped
    ports:
      - 9000:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "autoheal=true"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--ping=true"
      - "--ping.entryPoint=web"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:80/ping | grep -q 'OK' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  db:
    image: postgres:17
    volumes:
      - db-vol:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=donate_hope
      - POSTGRES_USER=dba
    restart: unless-stopped

volumes:
  db-vol:
