services:
  frontend:
    build:
      context: ./frontend
      args:
        - API_BASE_URL=http://localhost:8080
    ports:
      - 8081:80
    networks:
      - donate-hope-net
  backend:
    build: ./backend
    environment:
      DB_HOST: db
    ports:
      - 8080:7066
    networks:
      - donate-hope-net
      
  db:
    image: postgres:17
    volumes:
      - db-vol:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=donate_hope
      - POSTGRES_USER=dba
    networks:
      - donate-hope-net

volumes:
  db-vol:
networks:
  donate-hope-net:
    driver: bridge
